baseurl = "https://danielmangum.com"
title = "Daniel Mangum"
theme = "coder"
languagecode = "en"
googleAnalytics = "UA-116820283-1"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2" 
pygmentscodefences = true 
pygmentscodefencesguesssyntax = true

[params]
    author = "Daniel Mangum"
    info = "big fan of computers and human beings."
    description = "Daniel Mangum's personal website"
    keywords = "blog,developer,personal"

    disqusShortname = "yourdiscussshortname"

    colorScheme = "auto"
 
    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    customCSS = ["css/custom.css"]

    # Site Images
    images = ["images/twitter-card.png"]

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/hasheddan/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/hasheddan/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/danielmangum/"
[[params.social]]
    name = "RSS"
    weight = 4
    url = "https://danielmangum.com/index.xml"

# Menu links
[[menu.main]]
    name = "[RISC-V Tips]"
    weight = 1
    url  = "/risc-v-tips/"
[[menu.main]]
    name = "[RISC-V Bytes]"
    weight = 1
    url  = "/categories/risc-v-bytes/"
[[menu.main]]
    name = "[Blog]"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "[About]"
    weight = 3
    url = "/about/"
